trainer:
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ./logs
    name: curator-train
  _target_: pytorch_lightning.Trainer
  devices: 2
  default_root_dir: .
  min_epochs: null
  max_epochs: 1000
  enable_model_summary: true
  profiler: null
  log_every_n_steps: 10
  gradient_clip_val: 10.0
  gradient_clip_algorithm: norm
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: -1
  fast_dev_run: false
  overfit_batches: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  detect_anomaly: false
  precision: 32
  accelerator: auto
  num_nodes: 1
  deterministic: false
  inference_mode: false
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ./model_path
    save_top_k: 1
    monitor: val_total_loss
    filename: best_model_{epoch}_{step}_{val_total_loss:.2f}
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_total_loss
    min_delta: 0.0
    patience: 80
    mode: min
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch
  - _target_: curator.train.ExponentialMovingAverage
    decay: 0.995
    use_num_updates: true
task:
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0008
    eps: 1.0e-08
    betas:
    - 0.9
    - 0.999
    weight_decay: 0.01
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: true
    factor: 0.5
    patience: 80
  outputs:
  - _target_: curator.train.ModelOutput
    name: energy
    loss_fn:
      _target_: torch.nn.MSELoss
    loss_weight: 1
    metrics:
      mae:
        _target_: curator.train.PerAtomMAE
        size_key: n_atoms
        value_key: energy
      rmse:
        _target_: curator.train.PerAtomRMSE
        size_key: n_atoms
        value_key: energy
  - _target_: curator.train.ModelOutput
    name: forces
    loss_fn:
      _target_: torch.nn.MSELoss
    loss_weight: 200
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      rmse:
        _target_: torchmetrics.regression.MeanSquaredError
        squared: false
  - _target_: curator.train.ModelOutput
    name: virial
    loss_fn:
      _target_: torch.nn.MSELoss
    loss_weight: 1
    metrics:
      mae:
        _target_: curator.train.PerAtomMAE
        size_key: n_atoms
        value_key: virial
      rmse:
        _target_: curator.train.PerAtomRMSE
        size_key: n_atoms
        value_key: virial
  _target_: curator.model.LitNNP
  scheduler_monitor: val_total_loss
  warmup_steps: 0
  save_entire_model: true
  load_entire_model: false
  load_weights_only: true
  energy_weight: 1
  forces_weight: 200
  patience: 80
  virial_weight: 1
model:
  representation:
    _target_: curator.model.PainnModel
    num_interactions: 3
    num_features: 144
    cutoff: 5.0
    num_basis: 20
    cutoff_fn:
      _target_: curator.layer.CosineCutoff
      cutoff: 5.0
    radial_basis:
      _target_: curator.layer.SineBasis
      cutoff: 5.0
      num_basis: 20
  _convert_: all
  _target_: curator.model.NeuralNetworkPotential
  input_modules:
  - _target_: curator.layer.PairwiseDistance
    compute_neighbor_list: false
    compute_distance_from_R: false
  output_modules:
  - _target_: curator.layer.AtomwiseReduce
  - _target_: curator.layer.GradientOutput
    model_outputs:
    - forces
    - virial
    grad_on_edge_diff: true
    grad_on_positions: false
  - _target_: curator.layer.GlobalRescaleShift
data:
  _target_: curator.data.AtomsDataModule
  _convert_: partial
  datapath: test.traj
  train_path: null
  val_path: null
  test_path: null
  batch_size: 12
  compute_neighbor_list: false
  cutoff: 5.0
  num_train: 0.9
  num_val: 0.1
  num_test: null
  train_val_split: random
  shuffle: true
  num_workers: 0
  pin_memory: true
  species: null
  avg_num_neighbors: null
  atomic_energies: null
  normalization: true
  atomwise_normalization: true
  scale_forces: true
  transforms:
  - _target_: curator.data.MatScipyNeighborList
    cutoff: 5.0
    return_cell_displacements: true
  val_batch_size: 6
seed: 3407
cfg: config.yaml
model_path: test/model_path
run_path: .
deploy_model: true
compile: false
device: cuda
